apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep
spec:
  selector:
    matchLabels:
      app: my-app-1
  template:
    metadata:
      labels:
        app: my-app-1
    spec:
      containers:
      - name: app-1
        image: nigelpoulton/k8sbook:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
