apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    version: v1 
spec:
  containers:
  - name: hello-ctr
    image: nigelpoulton/k8sbook:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
