apiVersion: apps/v1beta2
kind: RelicaSet
metadata:
  name: replica-2

spec:
  replicas: 8
  selector:
    matchLables:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-ctr
          image: nigelpoulton/k8sbook:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080